"""empty message

Revision ID: 0081abd91089
Revises: 7e3a490158f6
Create Date: 2022-02-23 17:49:13.913923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0081abd91089'
down_revision = '7e3a490158f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'number')
    # ### end Alembic commands ###
